### ISSUE TITLE
Implementare la modalità a tempo

### ISSUE THREAD

**Issue by MircoPizzirani** [Francesco-02/MemoryDante#15]

**Comment by FrancescoPiazzi** [comment]
Far partire il timer al momento giusto dopo chiamando initTimer
Quando il tempo scade, far perdere la partita
Se il numero di secondi ha una cifra (ad es. quando manca un minuto e otto secondi) scrivere il tempo in formato 1:08 e non 1:8
(facoltativo semplice) Quando manca poco tempo far diventare il timer rosso
(facoltativo complicato e inutile ma figo) Quando manca poco tempo visualizzare i decimi di secondo
