### ISSUE TITLE
Implementare modlità a vite

### ISSUE THREAD

**Issue by MircoPizzirani** [Francesco-02/MemoryDante#16]

**Comment by FrancescoPiazzi** [comment]
Ogni coppia sbagliata, il numero di vite diminuisce in questo modo:
vite -= f(x)
dove x può essere il numero di tentativi sbagliati fino ad ora oppure il numero di tentativi sbagliati meno quelli giusti o altro.

Modellare la funzione f(x) in modo da incentivare il più possibile la memoria e scoraggiare il tirare a caso senza rendere il gioco impossibile
