### ISSUE TITLE
Creare un logo

### ISSUE THREAD

**Issue by FrancescoPiazzi** [Francesco-02/MemoryDante#22]

**Comment by FrancescoPiazzi** [comment]
Creare un logo da visualizzare nella barra delle schede del browser al posto di quel coso arancione di xampp
Si fa attraverso il file favicon.ico, che ovviamente andrà creato, esistono degli editor online

**Comment by Francesco-02** [comment]
Creare un logo da visualizzare nella barra delle schede del browser al posto di quel coso arancione di xampp
